export const profiles = [
  { id: 'ire', name: '이레', subtitle: '초등 1학년 · 과학·모험', count: 20, type: 'child', emoji: '🦖' },
  { id: 'iseol', name: '이설', subtitle: '초등 1학년 · 이야기·감정·만들기', count: 20, type: 'child', emoji: '🎨' },
  { id: 'isia', name: '시아', subtitle: '2~3세 · 그림·말놀이·생활습관', count: 20, type: 'toddler', emoji: '🐣' },
  { id: 'parent1', name: '부모 추천 1', subtitle: '최근 인기와 작품성을 함께 고려', count: 5, type: 'adult', emoji: '☕' },
  { id: 'parent2', name: '부모 추천 2', subtitle: '소설·교양·삶의 균형', count: 5, type: 'adult', emoji: '📚' },
];

export const catalog = [
  { id:'c001', title:'강아지똥', author:'권정생', audience:['ire','iseol'], tags:['그림책','생명','공감'], reason:'작고 하찮아 보이는 존재의 가치를 따뜻하게 보여줘요.' },
  { id:'c002', title:'몽실 언니', author:'권정생', audience:['ire','iseol'], tags:['문학','가족','역사'], reason:'부모와 함께 읽으며 가족과 시대 이야기를 나누기 좋아요.' },
  { id:'c003', title:'책 먹는 여우', author:'프란치스카 비어만', audience:['ire','iseol'], tags:['유머','독서','상상'], reason:'책 읽는 재미를 유쾌하게 느끼게 해줘요.' },
  { id:'c004', title:'마당을 나온 암탉', author:'황선미', audience:['ire','iseol'], tags:['문학','용기','성장'], reason:'조금 도전적인 함께 읽기 책으로 좋아요.' },
  { id:'c005', title:'아낌없이 주는 나무', author:'셸 실버스타인', audience:['ire','iseol'], tags:['관계','철학','그림책'], reason:'사랑과 관계를 두고 가족 대화를 시작하기 좋아요.' },
  { id:'c006', title:'틀려도 괜찮아', author:'마키타 신지', audience:['ire','iseol'], tags:['학교','자신감','발표'], reason:'실수와 발표에 대한 부담을 가볍게 해줘요.' },
  { id:'c007', title:'점', author:'피터 H. 레이놀즈', audience:['ire','iseol'], tags:['미술','자신감','창의'], reason:'작은 시도가 작품이 되는 경험을 보여줘요.' },
  { id:'c008', title:'느끼는 대로', author:'피터 H. 레이놀즈', audience:['iseol'], tags:['미술','감정','표현'], reason:'정답보다 자기 표현을 중요하게 느끼게 해줘요.' },
  { id:'c009', title:'종이 봉지 공주', author:'로버트 먼치', audience:['ire','iseol'], tags:['유머','주체성','모험'], reason:'전형적인 공주 이야기를 뒤집어 재미와 생각거리를 줘요.' },
  { id:'c010', title:'수박 수영장', author:'안녕달', audience:['ire','iseol','isia'], tags:['여름','상상','그림책'], reason:'상상력이 풍부하고 온 가족이 함께 보기 좋아요.' },
  { id:'c011', title:'할머니의 여름휴가', author:'안녕달', audience:['ire','iseol'], tags:['가족','여름','상상'], reason:'따뜻한 그림과 가족 정서가 매력적이에요.' },
  { id:'c012', title:'알사탕', author:'백희나', audience:['ire','iseol'], tags:['감정','관계','상상'], reason:'말하지 못한 마음을 이해하는 데 도움을 줘요.' },
  { id:'c013', title:'장수탕 선녀님', author:'백희나', audience:['ire','iseol'], tags:['유머','상상','가족'], reason:'한국적인 공간과 유머가 살아 있어 몰입하기 쉬워요.' },
  { id:'c014', title:'이상한 엄마', author:'백희나', audience:['ire','iseol'], tags:['가족','돌봄','상상'], reason:'돌봄과 가족의 따뜻함을 독특한 상상으로 보여줘요.' },
  { id:'c015', title:'구름빵', author:'백희나', audience:['ire','iseol','isia'], tags:['가족','상상','그림책'], reason:'짧고 따뜻하며 어린 동생과 함께 보기에도 좋아요.' },
  { id:'c016', title:'팥빙수의 전설', author:'이지은', audience:['ire','iseol'], tags:['유머','옛이야기','여름'], reason:'전래동화 같은 리듬과 반전이 재미있어요.' },
  { id:'c017', title:'친구의 전설', author:'이지은', audience:['ire','iseol'], tags:['친구','유머','관계'], reason:'친구 관계를 부담 없이 이야기하기 좋아요.' },
  { id:'c018', title:'눈아이', author:'안녕달', audience:['ire','iseol'], tags:['겨울','우정','감성'], reason:'계절감과 우정의 정서를 섬세하게 느낄 수 있어요.' },
  { id:'c019', title:'긴긴밤', author:'루리', audience:['ire','iseol'], tags:['문학','우정','생명'], reason:'부모와 함께 읽으면 오래 남는 성장 이야기예요.' },
  { id:'c020', title:'푸른 사자 와니니', author:'이현', audience:['ire','iseol'], tags:['동물','모험','성장'], reason:'동물과 모험을 좋아하는 아이가 빠져들기 좋아요.' },
  { id:'c021', title:'고양이 해결사 깜냥', author:'홍민정', audience:['ire','iseol'], tags:['생활','유머','시리즈'], reason:'글밥 있는 동화로 넘어갈 때 부담이 적은 인기 시리즈예요.' },
  { id:'c022', title:'낭만 강아지 봉봉', author:'홍민정', audience:['ire','iseol'], tags:['동물','모험','시리즈'], reason:'짧은 장과 빠른 전개로 혼자 읽기 연습에 좋아요.' },
  { id:'c023', title:'이상한 과자 가게 전천당', author:'히로시마 레이코', audience:['ire','iseol'], tags:['판타지','선택','시리즈'], reason:'재미와 함께 선택의 결과를 생각하게 해요.' },
  { id:'c024', title:'만복이네 떡집', author:'김리리', audience:['ire','iseol'], tags:['학교','판타지','시리즈'], reason:'저학년이 혼자 읽기 좋은 문장과 전개예요.' },
  { id:'c025', title:'아홉 살 마음 사전', author:'박성우', audience:['ire','iseol'], tags:['감정','언어','공감'], reason:'감정의 이름을 알고 표현하는 데 유용해요.' },
  { id:'c026', title:'화가 나서 그랬어!', author:'레베카 패터슨', audience:['ire','iseol'], tags:['감정','분노','생활'], reason:'화난 뒤의 마음과 행동을 자연스럽게 돌아보게 해요.' },
  { id:'c027', title:'나는 나의 주인', author:'채인선', audience:['ire','iseol'], tags:['자기결정','생활','철학'], reason:'스스로 선택하고 책임지는 감각을 길러줘요.' },
  { id:'c028', title:'왜냐면…', author:'안녕달', audience:['ire','iseol'], tags:['대화','상상','가족'], reason:'아이의 끝없는 질문을 재미있는 대화로 바꿔줘요.' },
  { id:'c029', title:'내 멋대로 슈크림빵', author:'김지안', audience:['ire','iseol'], tags:['유머','자존감','그림책'], reason:'각자의 개성과 장점을 즐겁게 보여줘요.' },
  { id:'c030', title:'슈퍼 토끼', author:'유설화', audience:['ire','iseol'], tags:['경쟁','회복','유머'], reason:'실패 뒤 다시 일어나는 과정을 유쾌하게 다뤄요.' },
  { id:'c031', title:'슈퍼 거북', author:'유설화', audience:['ire','iseol'], tags:['자기다움','경쟁','유머'], reason:'남의 기대보다 자기 속도가 중요하다는 메시지가 좋아요.' },
  { id:'c032', title:'공룡이 왔다', author:'박주현', audience:['ire'], tags:['공룡','상상','그림책'], reason:'공룡 관심을 상상 놀이와 연결해줘요.' },
  { id:'c033', title:'공룡은 긁지 않아', author:'르웬 팜', audience:['ire'], tags:['공룡','유머','생활'], reason:'공룡을 좋아하는 저학년이 가볍게 즐기기 좋아요.' },
  { id:'c034', title:'처음 만나는 야생 동물', author:'편집부', audience:['ire'], tags:['동물','과학','관찰'], reason:'사진과 짧은 설명 중심의 과학 입문서로 활용하기 좋아요.' },
  { id:'c035', title:'초등학생이 알아야 할 우리 몸 100가지', author:'어스본 편집부', audience:['ire'], tags:['과학','인체','지식'], reason:'질문 단위로 읽을 수 있어 과학 호기심을 채워줘요.' },
  { id:'c036', title:'초등학생이 알아야 할 우주 100가지', author:'어스본 편집부', audience:['ire'], tags:['우주','과학','지식'], reason:'짧게 나눠 읽기 좋고 그림 정보가 풍부해요.' },
  { id:'c037', title:'진짜 진짜 재밌는 공룡 그림책', author:'칼 멜링', audience:['ire'], tags:['공룡','지식','그림'], reason:'공룡 이름과 특징을 그림으로 오래 살펴보기 좋아요.' },
  { id:'c038', title:'과학자와 놀자!', author:'김성화·권수진', audience:['ire'], tags:['과학','인물','호기심'], reason:'과학을 외우는 지식보다 질문하는 태도로 만나게 해줘요.' },
  { id:'c039', title:'지구를 지켜라! 슈퍼 재활용 우주 비행선', author:'루스 퀘일', audience:['ire','iseol'], tags:['환경','만들기','상상'], reason:'재활용과 만들기 놀이로 확장하기 좋아요.' },
  { id:'c040', title:'도서관에 간 사자', author:'미셸 누드슨', audience:['ire','iseol'], tags:['도서관','규칙','감동'], reason:'규칙의 이유와 예외를 따뜻하게 생각하게 해요.' },
  { id:'t001', title:'사과가 쿵!', author:'다다 히로시', audience:['isia'], tags:['반복','동물','말놀이'], reason:'반복되는 소리와 큰 그림으로 함께 읽기 좋아요.' },
  { id:'t002', title:'달님 안녕', author:'하야시 아키코', audience:['isia'], tags:['잠자리','반복','그림책'], reason:'짧고 편안해 잠자리 루틴에 잘 맞아요.' },
  { id:'t003', title:'싹싹싹', author:'하야시 아키코', audience:['isia'], tags:['생활','반복','놀이'], reason:'일상 행동을 말놀이처럼 익힐 수 있어요.' },
  { id:'t004', title:'손이 나왔네', author:'하야시 아키코', audience:['isia'], tags:['옷입기','생활','신체'], reason:'스스로 옷 입는 과정과 연결하기 좋아요.' },
  { id:'t005', title:'싫어 싫어', author:'세나 게이코', audience:['isia'], tags:['감정','생활','자기표현'], reason:'싫다는 감정을 재미있게 인정하고 다룰 수 있어요.' },
  { id:'t006', title:'안 돼, 데이빗!', author:'데이빗 섀넌', audience:['isia'], tags:['생활','유머','규칙'], reason:'익숙한 말과 과장된 그림으로 아이가 크게 웃어요.' },
  { id:'t007', title:'배고픈 애벌레', author:'에릭 칼', audience:['isia'], tags:['숫자','자연','반복'], reason:'요일과 수, 성장 과정을 놀이처럼 접해요.' },
  { id:'t008', title:'갈색 곰아, 갈색 곰아, 무엇을 보고 있니?', author:'빌 마틴 주니어', audience:['isia'], tags:['색깔','동물','반복'], reason:'반복 문장 덕분에 아이가 쉽게 따라 말해요.' },
  { id:'t009', title:'아주아주 배고픈 애벌레', author:'에릭 칼', audience:['isia'], tags:['자연','음식','반복'], reason:'먹거리와 변화 과정을 선명한 그림으로 즐겨요.' },
  { id:'t010', title:'괴물들이 사는 나라', author:'모리스 샌닥', audience:['isia','ire','iseol'], tags:['감정','상상','가족'], reason:'화와 상상, 다시 돌아오는 안정감을 느끼게 해요.' },
  { id:'t011', title:'무지개 물고기', author:'마르쿠스 피스터', audience:['isia','ire','iseol'], tags:['친구','나눔','그림책'], reason:'반짝이는 그림과 단순한 이야기로 관계를 이야기하기 좋아요.' },
  { id:'t012', title:'곰 사냥을 떠나자', author:'마이클 로젠', audience:['isia'], tags:['리듬','신체놀이','반복'], reason:'소리와 동작을 곁들이면 즐거운 참여형 독서가 돼요.' },
  { id:'t013', title:'누가 내 머리에 똥 쌌어?', author:'베르너 홀츠바르트', audience:['isia'], tags:['유머','동물','관찰'], reason:'유아가 좋아하는 유머와 반복 구조가 강해요.' },
  { id:'t014', title:'기차 ㄱㄴㄷ', author:'박은영', audience:['isia'], tags:['한글','탈것','그림'], reason:'기차 그림을 보며 자음과 낱말을 자연스럽게 만나요.' },
  { id:'t015', title:'지원이와 병관이: 지하철을 타고서', author:'고대영', audience:['isia','ire','iseol'], tags:['생활','교통','가족'], reason:'익숙한 생활 장면을 세밀한 그림으로 살펴보기 좋아요.' },
  { id:'t016', title:'엄마 까투리', author:'권정생', audience:['isia'], tags:['가족','동물','감동'], reason:'부모의 사랑을 짧고 강한 이야기로 느낄 수 있어요.' },
  { id:'t017', title:'두드려 보아요', author:'안나 클라라 티돌름', audience:['isia'], tags:['참여','반복','상상'], reason:'문을 두드리며 다음 장면을 기다리는 참여형 책이에요.' },
  { id:'t018', title:'열두 띠 동물 까꿍놀이', author:'최숙희', audience:['isia'], tags:['동물','까꿍','반복'], reason:'까꿍 구조와 친숙한 동물로 집중하기 쉬워요.' },
  { id:'t019', title:'괜찮아', author:'최숙희', audience:['isia'], tags:['자존감','동물','반복'], reason:'아이의 작은 실패를 따뜻하게 안아주는 문장이 좋아요.' },
  { id:'t020', title:'나도 나도', author:'최숙희', audience:['isia'], tags:['자기표현','생활','반복'], reason:'따라 하고 싶은 유아의 마음을 잘 담았어요.' },
  { id:'t021', title:'어디 갔어?', author:'주리', audience:['isia'], tags:['찾기','관찰','그림책'], reason:'그림 속 단서를 찾으며 집중력과 말을 함께 키워요.' },
  { id:'t022', title:'똥이 풍덩!', author:'알로나 프랑켈', audience:['isia'], tags:['배변','생활습관','유머'], reason:'배변 훈련을 부담 없이 이야기하기 좋아요.' },
  { id:'t023', title:'치카치카 이를 닦아요', author:'편집부', audience:['isia'], tags:['양치','생활습관','반복'], reason:'양치 루틴과 바로 연결할 수 있어요.' },
  { id:'t024', title:'잘 자요, 달님', author:'마거릿 와이즈 브라운', audience:['isia'], tags:['잠자리','반복','안정'], reason:'차분한 반복 문장이 잠들기 전 안정감을 줘요.' },
  { id:'t025', title:'아빠, 더 읽어 주세요', author:'벤저민 쇼', audience:['isia'], tags:['가족','독서','잠자리'], reason:'부모와 책 읽는 시간을 즐겁게 만들어줘요.' },
  { id:'a001', title:'소년이 온다', author:'한강', audience:['parent1','parent2'], tags:['소설','역사','문학'], reason:'현재도 널리 읽히는 작품으로 깊은 독서 대화를 남겨요.' },
  { id:'a002', title:'안녕이라 그랬어', author:'김애란', audience:['parent1','parent2'], tags:['소설','관계','신작'], reason:'최근 독자 관심이 높은 한국소설 후보예요.' },
  { id:'a003', title:'채식주의자', author:'한강', audience:['parent1'], tags:['소설','문학','관계'], reason:'강렬한 문학적 체험을 원하는 독자에게 맞아요.' },
  { id:'a004', title:'작별하지 않는다', author:'한강', audience:['parent1','parent2'], tags:['소설','역사','기억'], reason:'역사와 기억을 섬세한 문장으로 다뤄요.' },
  { id:'a005', title:'모순', author:'양귀자', audience:['parent1','parent2'], tags:['소설','인생','관계'], reason:'오랫동안 꾸준히 사랑받는 생활 밀착형 소설이에요.' },
  { id:'a006', title:'불편한 편의점', author:'김호연', audience:['parent2'], tags:['소설','힐링','관계'], reason:'가볍게 읽히면서도 사람 이야기가 따뜻해요.' },
  { id:'a007', title:'아주 작은 습관의 힘', author:'제임스 클리어', audience:['parent1','parent2'], tags:['자기계발','습관','실용'], reason:'생활 루틴을 현실적으로 바꾸는 방법을 제시해요.' },
  { id:'a008', title:'도둑맞은 집중력', author:'요한 하리', audience:['parent1','parent2'], tags:['사회','집중','교양'], reason:'가족의 디지털 습관을 돌아보기 좋은 교양서예요.' },
  { id:'a009', title:'물고기는 존재하지 않는다', author:'룰루 밀러', audience:['parent1','parent2'], tags:['과학','에세이','철학'], reason:'과학과 삶의 의미가 섞인 흡입력 있는 논픽션이에요.' },
  { id:'a010', title:'나는 메트로폴리탄 미술관의 경비원입니다', author:'패트릭 브링리', audience:['parent2'], tags:['예술','에세이','회복'], reason:'바쁜 일상에서 천천히 바라보는 시간을 선물해요.' },
  { id:'a011', title:'세이노의 가르침', author:'세이노', audience:['parent1'], tags:['경제','자기계발','현실'], reason:'직설적인 조언을 선호할 때 읽어볼 만해요.' },
  { id:'a012', title:'트렌드 코리아 2026', author:'김난도 외', audience:['parent1'], tags:['경제','트렌드','사회'], reason:'현재 소비와 사회 흐름을 빠르게 훑기 좋아요.' },
  { id:'a013', title:'어른의 행복은 조용하다', author:'태수', audience:['parent2'], tags:['에세이','삶','회복'], reason:'짧게 나눠 읽으며 일상을 정돈하기 좋아요.' },
  { id:'a014', title:'이처럼 사소한 것들', author:'클레어 키건', audience:['parent2'], tags:['소설','윤리','문학'], reason:'짧지만 오래 생각하게 하는 밀도 높은 소설이에요.' },
  { id:'a015', title:'파친코', author:'이민진', audience:['parent1','parent2'], tags:['소설','가족','역사'], reason:'가족과 시대를 긴 호흡으로 따라가는 작품이에요.' }
];
